apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "Current time: $(date)" >> /shared/data.txt
                sleep 5
              done
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
        - name: multitool
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "Reading file content:"
                cat /shared/data.txt
                sleep 10
              done
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
